### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by tokazio** [urish/java-openal#4]
Nice work! I was using the lwjgl3 but it need a lwjgl lib with the openal one.
The SourceOutputStream is a huge addition! 

2 things:
_ on osx, 'soft_oal' is 'openal' (it need to change the file name or make a symlink)

_ I think it will be best if the number of cycling buffers  in SourceOutputStream was configurable.
In my case i need more than 2 for not stuttering.

**Comment by urish** [comment]
Thanks!

The first thing was fixed by #2, about the second thing - feel free to implement and send a PR.

Thanks!
