### ISSUE TITLE
`Source.setPosition()` does not work.

### ISSUE THREAD

**Issue by Brahvim** [urish/java-openal#7]
**I'm very sorry!**
I should not speak about fixing such an old library! Please forgive me for perhaps wasting your time...

# The issue:
According to my tests, class `Source`'s `setPosition()` does not do anything. Calling `ALFactory`'s `al.alSource3f()` with my source's ID throws a `NullPointerException`.

Perhaps this is own my mistake, but since class `Source`'s `setPosition()` method does not do anything anyway, I assume that it might be a problem with the library itself.

I am using your library inside [Processing 3.5.4](https://github.com/processing/processing), which, as far as I remember, uses Java 8.

Again, I am very sorry if this GitHub issue feels like it is bothering.

**Comment by urish** [comment]
Thanks for reporting! 

You are not bothering. GitHub issues is exactly the place for reporting these kind of things. It's my bad for not archiving this repository. I'll be archiving it now, and if anyone wants to keep maintaining it, they are welcome to fork it.
